In [23]:
class Employee:
  count=0
  def __init__(self,name,family,salary,department): #initializing with constructor method
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.count+=1
  def avgsal(employees): #average salary function
    totalSalary=sum(emp.salary for emp in employees)
    return totalSalary/len(employees) if employees else 0
class fulltimeEmployee(Employee):
  def __init__(self,name,family,salary,department):
    super().__init__(name, family, salary, department)
emp1 = Employee("mani","allada",16000,'IT') #object 1
emp2 = Employee("vanitha","chintalapudi",20000,'Tech') #object 2
fulltime_emp1=fulltimeEmployee("aravind","komandla",50000,"Service")
employees=[emp1,emp2,fulltime_emp1]
print(Employee.count)
print(Employee.avgsal(employees))

3
86000
28666.666666666668


In [90]:
import numpy as np
vc=np.random.uniform(1,20,20) #creating randon 20 numbers
a=vc.reshape(4,5) #reshaping it into array
max_elements = np.amax(a, axis=1) #finding max element of each row
max_elements = max_elements[:, None] #storing them in to list
new_arr = np.where(a == max_elements, 0, a) #changing those elements to 0
print(new_arr)

[[14.75154062  7.34927153 15.94482584  0.          4.76190746]
 [13.73089697  9.17371228  6.22132119  0.          9.09090622]
 [ 7.31750543  0.         18.01382495  1.28990034  9.10758138]
 [ 6.16383947  0.         13.45571319 14.06599938 18.23545928]]


https://drive.google.com/file/d/14b37_dMEDcLSKv4c9axbzB6vBPuNAG0W/view?usp=drive_link